baseurl = "https://michaelhealy.space/"
title = "Michael Healy"
copyright = "&copy; 2018 Michael Healy"
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
publishdir = "mjh16.github.io"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]
# Color theme.
#   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
color_theme = "default"

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
  font = "classic"

  # Your details.
  name = "Michael Healy"
  role = "Graduate Teaching Assistant in Rhetoric and Composition"

  # Organizations/Affiliations.
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ {name = "Florida State University", url= "https://english.fsu.edu"} ]
  gravatar = false
  avatar = "portrait.jpg"
  email = "mhealy@fsu.edu"
  address = "Williams 329, Florida State University, Tallahassee FL, 32306, USA"
  office_hours = "Summer 2018: email for appointment"
  phone = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Enable/disable map in Contact widget.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 1
  map_api_key = "AIzaSyBsE4hpY0WAuctPM052Xls6hlh3migTC9A"
  latitude = "30.440116"
  longitude = "-84.291954"
  zoom = 15

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"

  # Show estimated reading time for posts?
  reading_time = false

  # Display comment count? Requires commenting to be enabled.
  comment_count = false

  # Display next/previous section pager?
  section_pager = true

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = false
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ["garnet.css"]
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to Go's date format: http://fuckinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

    # Social/Academic Networking
    #
    # Icon pack "fa" includes the following social network icons:
    #
    #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
    #   youtube, instagram, soundcloud
    #
    #   For email icon, use "fa" icon pack, "envelope" icon, and
    #   "mailto:your@email.com" as the link.
    #
    #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
    #
    # Icon pack "ai" includes the following academic network icons:
    #
    #   google-scholar, arxiv, orcid, researchgate, mendeley
    #
    #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:mhealy@fsu.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/mhealy_rhet"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/mjh16"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 1

#[[menu.main]]
#  name = "Publications"
#  url = "#publications"
#  weight = 2

[[menu.main]]
  name = "Presentations"
  url = "#talks"
  weight = 3

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 5

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 5
  identifier = "projects"

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  series = "series"
  activity = "activities" #Scholarly Activities not covered in talks presentations, publications, or teaching. Think of this as a way to chunk classes, research, digital studio work, etc together. Could just be a way for me to classify, could also be useful as a means of presenting and linking things

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
